import { Gender, Race, NameGenerationTable } from './domain'

export const defaultNameArchive: NameGenerationTable = {
  [Race.Human]: {
    first: {
      [Gender.Male]: [
        'Andris',
        'Arnould',
        'Balan',
        'Bertie',
        'Cannute',
        'Clovis',
        'Damian',
        'Dorian',
        'Elmar',
        'Epicurus',
        'Fawkes',
        'Franz',
      ],
      [Gender.Female]: [
        'Maeve',
        'Maub',
        'Fiona',
        'Grain',
        'Isolde',
        'Eos',
        'Mary',
      ],
    },
    last: [
      'Tiberius',
      'Vespasian',
      'Octavius',
      'Titus',
      'Valerian',
      'Numerian',
      'Maximus',
      'Jovian',
      'Niell',
      'Ollain',
      'Ri',
      'Slanuill',
      'Labrainne',
      'Lardonn',
      'Fail',
    ],
  },
  [Race.Dwarf]: {
    first: {
      [Gender.Male]: [
        'Baird',
        'Paden',
        'Connach',
        'Morven',
        'Beathan',
        'Dougal',
        'Tam',
        'Murdoe',
        'Rab',
        'Akir',
        'Alpin',
        'Amhuinn',
        'Athol',
        'Bac',
        'Baen',
        'Balgaire',
        'Bhreac',
        'Brochan',
        'Brodee',
        'Broehain',
        'Caladh',
        'Dearg',
        'Diarmad',
        'Domhnall',
        'Donnachadh',
        'Dubhghall',
        'Eanraig',
        'Fearchar',
        'Frangag',
        'Goraidh',
        'Gowan',
        'Harailt',
        'Iver',
        'Kade',
        'Keeley',
      ],
      [Gender.Female]: [
        'Marcail',
        'Senga',
        'Sorcha',
        'Ailsa',
        'Liùsaidh',
        'Morag',
        'Cadha',
        'Caitir',
        'Beileag',
        'Curstaidh',
        'Gormlaith',
        'Fionola',
        'Jeanie',
        'Leagsaidh',
        'Maidie',
        'Malmuira',
        'Nathiara',
        'Robena',
        'Stineag',
        'Teasag',
        'Wynda',
      ],
    },
    last: [
      'Granitehold',
      'Oakhelm',
      'Rowanshield',
      'Redtorc',
      'Hillpipe',
      'Sheeraxe',
    ],
  },
  [Race.Elf]: {
    first: {
      [Gender.Male]: [
        'Anaeirin',
        'Elian',
        'Glyn',
        'Hywel',
        'Idris',
        'Llewelyn',
        'Maelon',
        'Peredur',
      ],
      [Gender.Female]: [
        'Anwen',
        'Bronwen',
        'Eluned',
        'Gwenfrewi',
        'Kerwyn',
        'Maelona',
        'Morwen',
      ],
    },
    last: ['Dwyfed'],
  },
  [Race.Halfling]: {
    first: {
      [Gender.Male]: ['Wilber', 'Eugene'],
      [Gender.Female]: ['Peggy', 'Tabbatha'],
    },
    last: ['Goodman', 'Lightfoot'],
  },
}
